<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>a27520e5-adb9-45b9-9d51-29b2f65bda14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d4c269c-20f9-47a8-a57e-ffa03c9bee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>cfeb91fc-ed6c-4130-bb69-bf22a1ae6b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27853','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')</value>
      <webElementGuid>b6325132-ee30-49f9-8e5c-72506486c2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>047dc1fc-8c4d-4014-bacc-1bb84ac17027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>033be1af-c3ff-473d-9301-df427cb9813e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru/Page_New Confins - Main/Page_New Confins - Main/Page_New Confins - Main/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>cf0767e5-98b6-4f02-893b-8c5dafd714f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>8ffc2fb0-0d24-4cf2-b918-89c4c530e299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>2f279147-64ec-48f7-aef4-9aebd3fe1815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>e236f983-2940-409a-b806-ebb80966be84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPMOPIN'])[1]/following::a[1]</value>
      <webElementGuid>6f2c17f3-0c83-494a-92ae-512036b0d73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL'])[1]/following::a[1]</value>
      <webElementGuid>d7034e40-42d7-4e2b-b3b5-fa5cdb4a14ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEMBIAYAAN MULTIGUNA INSTALLMENT PAYMENT 2W NEW BIKE - REGULER'])[1]/preceding::a[1]</value>
      <webElementGuid>39e22862-fc45-45ed-ab3b-048fc36f9174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPNB0000'])[1]/preceding::a[1]</value>
      <webElementGuid>a84c36e8-869f-49af-a939-2b70391ee32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>0a1d9605-d569-45dd-8fe9-8dca51fe4d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27853','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')&quot;)]</value>
      <webElementGuid>7d982cb8-d63e-4f52-b4d8-596935da0d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>401f685b-defc-405f-b3ae-37f7694a9b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:ProductOfferingLookup(&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;27853&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MGIPMOPIN&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>60753622-1fb9-4dea-b338-9356aece95e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
