<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>1be6bbe0-94cc-4db2-9f43-aabf173b04f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e2eea2e-fe92-4d10-9dd5-b0087f91190c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>4fd96527-6320-44ba-8766-fd141b5717dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27853','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')</value>
      <webElementGuid>390c9163-1857-4b1c-a639-bf69619339f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>486c2ecc-e353-4fe7-913a-3aee611cdf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>588f2ee0-df1e-4f4e-b1da-d64e2ecffaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru/Page_New Confins - Main/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>5e71a29e-fc65-41a7-ab8d-26dbe2ba3728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>f4d5ce37-8d59-4de8-9f94-c0a279e21371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>2c463225-ae6c-480c-998c-06d222457d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>14fa152c-812e-4efe-b3ee-5760f27590ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPMOPIN'])[1]/following::a[1]</value>
      <webElementGuid>ae8334e5-c164-452d-bca2-fda0604ab0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL'])[1]/following::a[1]</value>
      <webElementGuid>2e08b781-b51c-4605-bb8a-9c734bc98117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEMBIAYAAN MULTIGUNA INSTALLMENT PAYMENT 2W NEW BIKE - REGULER'])[1]/preceding::a[1]</value>
      <webElementGuid>cd380d1d-a079-415e-86f2-a5eb092d05eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPNB0000'])[1]/preceding::a[1]</value>
      <webElementGuid>3e0dcae5-3a7b-4bff-919d-132e400fe51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>f8f650a9-5b02-4d78-8ddb-6faf1a267ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27853','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')&quot;)]</value>
      <webElementGuid>adf5bcbe-dc7a-4381-94fb-67de77744aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>df46f25b-8113-400d-bcce-04fa034ac256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:ProductOfferingLookup(&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;27853&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MGIPMOPIN&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>fe69ec09-b125-477e-a66a-d46d4d011b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
