<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Offering Name_ucLookupProdOfferuclProductOfferingimb</name>
   <tag></tag>
   <elementGuidId>95a386f5-c69a-4d53-9872-9ff8d07fc9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe6103ee-fd56-4247-b905-d6e09b3193d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>28f9f2b3-9f05-434c-a9c7-4b4b7f83cfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupProdOffer$uclProductOffering$imb</value>
      <webElementGuid>ba889dc0-2a97-49c6-b054-00eb41341b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_imb</value>
      <webElementGuid>9604660d-9e72-465f-862f-49f147fb7554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>1b3f7173-0fb0-4b16-868f-5d5fa0c5ad2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupProdOffer_uclProductOffering');</value>
      <webElementGuid>54262e00-d308-4a79-ac55-6a214dce1140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_imb&quot;)</value>
      <webElementGuid>cc63524c-0ca1-4611-a5e8-6cb2bc67ac17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru/Page_New Confins - Main/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>1033aec7-c293-4dc4-8336-2da04b8bf55f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      <webElementGuid>9497e343-3992-4ba7-bd76-d3cb91573b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table/tbody/tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>52c7c22e-39ba-42a8-9ec5-46b91e201eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>3a4f16e3-1c82-45b2-be2e-adba6523c59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupProdOffer$uclProductOffering$imb' and @id = 'ucLookupProdOffer_uclProductOffering_imb' and @src = '../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>ed5d73de-749d-4129-b979-74dea49a7f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
