<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_login</name>
   <tag></tag>
   <elementGuidId>5bee1edc-37bf-475b-b7db-30fe5675b30a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d49a8e5-e7bc-4947-98f2-92368dd74386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87901c14-4659-4aac-b43f-18f12e06328b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>d0b5905d-c305-4a59-8416-670665926235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>124ae5cb-42f0-429e-a6bf-e12e24c80c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerLoginClick();__doPostBack('lbLogin','')</value>
      <webElementGuid>361b3de9-2d24-4cd0-ac99-72cf0ee87c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>c8c6b113-3556-451e-a44d-e27e3e35cf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbLogin&quot;)</value>
      <webElementGuid>412c3916-c33f-42a0-929a-a127d7ba7586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbLogin']</value>
      <webElementGuid>c5a4eb4d-46af-4dee-8df2-3634de5625e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upButton']/div/input</value>
      <webElementGuid>ad17ef3e-5ea3-4402-b289-936438ba2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3c1b97d0-63a1-4882-a7b0-9d6a3b29879f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'lbLogin' and @id = 'lbLogin']</value>
      <webElementGuid>74d734f2-9335-4622-bad9-b5aac896b71e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
