<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCHBARU</name>
   <tag></tag>
   <elementGuidId>1f081aee-c7a6-40c8-8547-dedd6b2ba59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fa8ad20-65b1-4cb1-a0fe-36943060f5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>914670cc-1842-4a4f-abb7-6aae4debac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>d308abe6-822b-4061-8e49-001b132db61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>ff9da0e5-8161-429e-a5c0-1b5e35c87969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>452328c9-69b0-4f1d-b935-9736549e183e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>79e01b18-d416-45ae-8cc4-5d9bcd98b0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Page_New Confins Bro/iframe_Term  Condition_appForm</value>
      <webElementGuid>ec904098-4f96-45c3-97a0-5c378f1729d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>6708e2fa-0997-45d5-a735-26b28fa3183b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uclCust_uclCust_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>860e63e5-6b61-47f8-bd90-b2bbcd65e2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH')]</value>
      <webElementGuid>aa3d09f0-8695-407b-8236-afda4b3b1630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::a[1]</value>
      <webElementGuid>52ad747d-22fb-43f7-a767-24cfdba2f70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/following::a[1]</value>
      <webElementGuid>d9db703b-1fd4-4364-ad34-ed1e101bd07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/preceding::a[1]</value>
      <webElementGuid>bf239c35-8373-4284-be04-35cafca3e31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Model'])[1]/preceding::a[2]</value>
      <webElementGuid>b565c59a-9051-45fc-b0ce-3675200e441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>506da3ce-fc8e-48f9-9c4f-8baf4631fb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>5b7d2e6d-6252-4c38-bcd2-86bfc13edcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>7d47860e-7f77-42ac-9b21-12aaafac2774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>03da0cab-e776-4a0d-8642-3d8b740e9a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
