<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal</name>
   <tag></tag>
   <elementGuidId>8c89dfe4-cdc5-4e9e-8737-6a8c8f84eea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblCustType_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCustType_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e97c9e80-6672-468b-9d47-902dfa053f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCustType_0</value>
      <webElementGuid>3f15af86-ba63-4bd2-8407-55939fbaf0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f8e2dcc9-4d34-426b-bf65-f0f947e0bd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCustType</value>
      <webElementGuid>d83c523e-1426-44db-a446-b5761aa8ffed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>c840ac01-1f8d-4794-98dd-13dd907c3d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>6375a3fd-c4ae-4601-9ab5-ac9df3bcd5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCustType_0&quot;)</value>
      <webElementGuid>d18a0781-1119-4dbc-8ce7-f877f98eca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>605532b6-66de-4392-8f23-689fa59f08b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCustType_0']</value>
      <webElementGuid>112fa98f-5bc8-437d-8922-fcf3ba1ba47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCustType']/tbody/tr/td/input</value>
      <webElementGuid>11a34cb8-22eb-4f90-9a56-7f7d71e3faa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>832e6e37-88dc-4760-979f-d81b656a1200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCustType_0' and @type = 'radio' and @name = 'rblCustType' and @checked = 'checked']</value>
      <webElementGuid>53d2fcbb-1ed3-4d5e-9a7c-d395fb97bc9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
