<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number</name>
   <tag></tag>
   <elementGuidId>0d9cd4fc-6c72-450d-babb-7f531fb2080d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucIdCust_txtCustIdNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>601f11c6-5abd-4ec1-a8f6-97695b4271f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucIdCust$txtCustIdNo</value>
      <webElementGuid>7bcec041-57fc-45cc-b7f6-9f985504c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebec06cd-bd9f-48bd-b044-e7aeaa6389bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3173042711880007</value>
      <webElementGuid>f9d31ba3-c1ef-4312-bb2a-35230c7b6d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cba49238-55cc-4956-9b72-352ca24de0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucIdCust_txtCustIdNo</value>
      <webElementGuid>c4e9dd52-ac98-4528-862b-59ba8c50ce69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a4f2b0dc-16ac-45cb-9d13-3015032d1269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtMedInputStyle</value>
      <webElementGuid>70912218-88cc-4c22-9939-7b2df65cd271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucIdCust_txtCustIdNo&quot;)</value>
      <webElementGuid>fb45dc6a-f619-4ec1-aad1-bc6721733fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>08db23ff-f3dc-4ef8-914f-b3782259196f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      <webElementGuid>f4487f62-aa10-4ee8-853e-14c73809c05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoID']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1127c740-2730-4208-b4d4-95471cea8fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>bcc7fc7d-618e-46da-a407-7399ba687528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucIdCust$txtCustIdNo' and @type = 'text' and @id = 'ucIdCust_txtCustIdNo']</value>
      <webElementGuid>9a12bc73-21e6-4e79-877f-ac5a762d03bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
