<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company</name>
   <tag></tag>
   <elementGuidId>d521ba56-6e2f-497a-aecb-80de2507fb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblCustType_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCustType_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e729f567-fcc9-4a4d-9992-8813943fb431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCustType_1</value>
      <webElementGuid>eda2404c-ccdf-4088-997d-415bbad2f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6090e540-2aea-4778-9de7-609558596818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCustType</value>
      <webElementGuid>d3fdb41e-9436-406e-97e3-b1b0a51a3adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>291b4ce5-c583-4dc7-a398-880d243b92d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblCustType$1\',\'\')', 0)</value>
      <webElementGuid>d903a198-c38c-4b98-83ab-9f1fe96b34a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCustType_1&quot;)</value>
      <webElementGuid>78fe8c57-2703-4b46-91e6-d09826ee1338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>53b37a49-b5a2-4ceb-9553-9a178a2bf402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCustType_1']</value>
      <webElementGuid>285b1e9d-ad0c-4fb7-ab62-7d4ac2f3c359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCustType']/tbody/tr/td[2]/input</value>
      <webElementGuid>4535abad-1d5a-485f-a3f4-45ff598bbf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7e202937-3a2f-411d-ba2a-fe0b427fc07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCustType_1' and @type = 'radio' and @name = 'rblCustType']</value>
      <webElementGuid>4f1c79c2-e31e-4973-84ac-6f3597f147c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
