<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPWP</name>
   <tag></tag>
   <elementGuidId>96e10d34-3c78-401c-aa40-2359d7050934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNpwp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNpwp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edfbc805-e5f0-4c2a-ab49-166e6e8d6cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNpwp</value>
      <webElementGuid>e8473168-1ebe-4552-b085-317044acf1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8f2fda4-1ee1-4a71-859c-d7571e96b780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3173042711880007</value>
      <webElementGuid>4402c94d-5fd8-4f46-8892-f7500b0ae14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>3b3c6e75-98e8-41f4-ae7f-c63afac94448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNpwp</value>
      <webElementGuid>7998cffa-bce4-4f1e-b039-b0faa7736517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>9564324b-ade6-4f46-809c-8ed561bab7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtMedInputStyle</value>
      <webElementGuid>2f4b825a-1fee-4ae0-b707-13cf531ca9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNpwp&quot;)</value>
      <webElementGuid>26cd8511-619c-48a4-99f4-ab1dd594f9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>8189baa1-08f5-43ff-9a65-bf6a07481d46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNpwp']</value>
      <webElementGuid>78f87393-a39c-4a01-abe2-9664b2f74b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableCust']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>ce9380cd-ba3b-48d8-a4b5-ae100b36233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>71ab2632-cda0-4d14-98db-5a845bf21a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtNpwp' and @type = 'text' and @id = 'txtNpwp']</value>
      <webElementGuid>70339efc-5e0f-4640-9041-e4c45f8629c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
