<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Offering Name_ucLookupProdOfferuclProductOfferingimb</name>
   <tag></tag>
   <elementGuidId>e332a798-dcf6-456f-a977-16fd50e926ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d94ff10a-8c65-400d-87c5-d2bd8de83960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>021b0c9e-cc1b-4ec4-98e2-869ad28c83fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupProdOffer$uclProductOffering$imb</value>
      <webElementGuid>0536531c-c616-4027-9b22-faa4e6339d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_imb</value>
      <webElementGuid>66112bb4-edfe-4692-b170-a906c22739a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>d63997da-b428-4c4f-b75a-6f43b27a3756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupProdOffer_uclProductOffering');</value>
      <webElementGuid>b4b4befb-0993-4511-8526-e81f96ed9d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_imb&quot;)</value>
      <webElementGuid>d8bd5f9c-47b7-4fb3-a041-43b8e05dd48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru2/Page_New Confins - Main/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>ab3c16f1-120e-46e4-a5e6-ffdd14dd3043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      <webElementGuid>df6d7612-e7a5-4e4d-b0ac-7d65c4d5dc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table/tbody/tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>9c968dfe-f89f-4eea-ba74-3e5de29cac44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>db701b41-1de5-4bf4-b2d2-d78183fa5d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupProdOffer$uclProductOffering$imb' and @id = 'ucLookupProdOffer_uclProductOffering_imb' and @src = '../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>68ac327d-9e85-40f8-ab32-094aaf7a1ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
