<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Offering Name</name>
   <tag></tag>
   <elementGuidId>6395e51d-d156-4397-a29f-1052f6f48a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[5]/div[3]/div/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div[1]/div/table/tbody/tr[1]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372a3835-7d62-4706-b076-9e527fbe67ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupProdOffer$uclProductOffering$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue</value>
      <webElementGuid>0c50c93e-2def-4417-95c8-2d200bf0c92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6782a19-e6ef-4a34-b9c4-7afa85d0a3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      <webElementGuid>491bfd18-27b8-430f-b894-8ebed7330e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>a51010f7-2b9f-4d2a-a1a1-42e12dd37f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1&quot;)</value>
      <webElementGuid>cc4c5a52-db4b-4668-bdde-ba99f8444243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>ca0b142a-7edf-46de-b630-9739f888c3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>67e40957-4706-4ba1-b251-d05f55917b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>9a81c483-a255-4b86-a15c-0b3d140d55c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucLookupProdOffer$uclProductOffering$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue' and @type = 'text' and @id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>119ac849-f3f0-48dd-843f-26ef3d886f19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
