<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGOUT</name>
   <tag></tag>
   <elementGuidId>0e3b3624-fe84-41af-9781-e6a2a9f5fac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navLogout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navLogout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d714f951-b230-4f90-b22a-6cd97910c561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure you want to quit?');</value>
      <webElementGuid>15dfdb39-37e9-41a5-ba00-4380b7b4438d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navLogout</value>
      <webElementGuid>4ef6c990-5490-4e3d-a49d-15f5d1eccb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('navLogout','')</value>
      <webElementGuid>973237ca-e14f-4eec-9691-9ae0b89a5848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>a13f987e-431b-4fa7-ac66-73cda082c1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navLogout&quot;)</value>
      <webElementGuid>a019424a-6e0d-4246-bfd0-ed317cc88f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navLogout']</value>
      <webElementGuid>4dd6ed9a-c3f3-47e4-9ad2-5c3d70967c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navMenu']/a</value>
      <webElementGuid>8ad55121-477c-499d-bacb-4014bdfd743b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGOUT')]</value>
      <webElementGuid>723a7ff3-e579-4918-a367-631175ee11c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday, 06 February 2024'])[1]/preceding::a[1]</value>
      <webElementGuid>a37632ba-05be-46cb-bc50-2ff46deaaf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, Nova Dwihartanto, MALANG, Credit Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>80153225-4d92-444e-9b65-8e53b1cfaf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>60279736-ee0f-412a-9c98-807fd7502dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('navLogout','')&quot;)]</value>
      <webElementGuid>96beb114-90ac-476f-8760-0a5f5189f809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>87968dac-cc6f-4ad7-a51c-dccebd8d5fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navLogout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;navLogout&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>b1c08ade-df25-40e5-a500-b7e2d21f54ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
