<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome, Anita Gusti, KEDOYA, Credit Admin_imgMenu</name>
   <tag></tag>
   <elementGuidId>7e014aba-7020-45fb-a11b-c809e226f103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c82bb845-d261-47fc-a6c9-56595785b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgMenu</value>
      <webElementGuid>e698cd32-1338-49b9-9e68-7b724c596b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/menu.png</value>
      <webElementGuid>d2dde16f-ddfc-494c-802c-a03990a10118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgMenu&quot;)</value>
      <webElementGuid>f8ba093b-5108-4862-9a8d-51802d97c60a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgMenu']</value>
      <webElementGuid>339d1935-c79b-4707-9837-8587722135df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuPadding']/img</value>
      <webElementGuid>6a30f2cd-236f-47f0-ba70-6e55d2a5a2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>76d82d70-d1d1-4ad2-858d-65ed53f8586c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgMenu' and @src = 'Images/menu.png']</value>
      <webElementGuid>0c479bb1-7811-4a29-9ead-4b7c3be5d893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
