<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APLICATION NUMBER</name>
   <tag></tag>
   <elementGuidId>26e1b413-5fa3-46c0-ba32-b6ef3ee279c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucCreditProcessMainInfo_lbAppNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06858f74-2627-4602-80ed-ebe26dcbe329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCreditProcessMainInfo_lbAppNo</value>
      <webElementGuid>0cf865a0-24bb-4a19-bfd4-ae53d1c5092d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')</value>
      <webElementGuid>abfb93cb-89e4-4e9f-bc0a-67c6f2b3f76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>504APP20240200259</value>
      <webElementGuid>f2c4168b-d9b1-4aaa-a1f4-98cb8127136b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucCreditProcessMainInfo_lbAppNo&quot;)</value>
      <webElementGuid>267a1c41-7d50-4fdf-8360-03d4dd87339a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>93260097-f29d-458c-8caa-8e0eafa66627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      <webElementGuid>8a5f1468-a7c9-4550-b268-99126f2db3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainInfoUC']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>e1770b58-ba95-437d-96dc-2f01ae197d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'504APP20240200259')]</value>
      <webElementGuid>37c419bd-17a4-4ed6-84de-13fb8a1843a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Number'])[1]/following::a[1]</value>
      <webElementGuid>da169188-1a19-4202-8e8b-dee1e59477a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Info'])[1]/following::a[1]</value>
      <webElementGuid>1b2faa12-0be4-4035-b3af-b12932c4a976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num Of Asset'])[1]/preceding::a[1]</value>
      <webElementGuid>a20fa152-89f8-45cb-a1b7-79acdc7522a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Office'])[1]/preceding::a[1]</value>
      <webElementGuid>606cbc56-cb4a-4f4c-8201-5a39798a74a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='504APP20240200259']/parent::*</value>
      <webElementGuid>c333a4d2-7fb3-4d4d-9baa-b8e2bf18d87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')&quot;)]</value>
      <webElementGuid>758ad3df-ae88-4f54-8926-783314d0c5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>0d2503d3-324f-4bb0-9fa9-06bcb151ee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucCreditProcessMainInfo_lbAppNo' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ucCreditProcessMainInfo$lbAppNo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '504APP20240200259' or . = '504APP20240200259')]</value>
      <webElementGuid>2584356c-ca0e-4aa4-a396-64bdb3c2eeb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
