<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Term  Condition_appForm</name>
   <tag></tag>
   <elementGuidId>07ecb766-76a6-489b-b0f6-cc2898d056fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='appForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>595de3a3-cebc-4318-be33-4e6e59ff0915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ReferantorData/ReferantorDataX.aspx?AppId=1631916&amp;AppSrc=</value>
      <webElementGuid>25f1512a-9b70-4cca-860a-9e11b3976817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>20f4e461-625e-4788-8509-fe23a7066d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>39607794-66ad-48f0-b491-313595856abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c567f61-4b4e-414b-9325-c4f069e3a178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appForm&quot;)</value>
      <webElementGuid>329584a5-5698-488e-acac-099aa5cd23db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage</value>
      <webElementGuid>28d7d4af-00c5-4fa7-9110-1ed2755ef586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='appForm']</value>
      <webElementGuid>9c36656c-e41c-4b4b-aa07-861a93c3ffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appFormContainer']/iframe</value>
      <webElementGuid>6db6141c-70d2-4337-9424-c979bf8504ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>33a69662-7261-4d0c-9c1a-1d36a9528e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ReferantorData/ReferantorDataX.aspx?AppId=1631916&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>bcb5c13a-9f2e-4383-8fba-546e7eb15bef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
