<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code</name>
   <tag></tag>
   <elementGuidId>4951eb6f-935d-4bbf-9c40-7b06ae94f9e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_ucLookupZipCode_uclZipCode_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_ucLookupZipCode_uclZipCode_txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7911d1e7-0b8d-4a28-9ac1-a3f6a937996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$ucLookupZipCode$uclZipCode$txt</value>
      <webElementGuid>5077e8af-5061-45ff-bed3-5c38fabe802a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>240fbb92-a14d-44f8-9e8f-2844f457fd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucAddr$ucLookupZipCode$uclZipCode$txt\',\'\')', 0)</value>
      <webElementGuid>724ca167-408e-4a80-b470-35dedd4e8dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>538032c4-2e33-4f4a-9b78-02b5860c8adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_ucLookupZipCode_uclZipCode_txt</value>
      <webElementGuid>5643cccd-51d2-4c73-844d-a80cd7dd061e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>11b78450-8bc3-4331-b068-2d7a62ad453a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>keyIdUp(event,this,'ucAddr_ucLookupZipCode_uclZipCode_li','ucAddr_ucLookupZipCode_uclZipCode_lt','ucAddr_ucLookupZipCode_uclZipCode_hdn','0');</value>
      <webElementGuid>377e5b29-b0e4-4510-87aa-0f4941cf453d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_ucLookupZipCode_uclZipCode_txt&quot;)</value>
      <webElementGuid>e33bc06f-c741-4f04-9636-70c249ca5d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>fa75d203-49e9-42a9-9d3d-639183f89d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_ucLookupZipCode_uclZipCode_txt']</value>
      <webElementGuid>dffa71b1-f431-47aa-8228-af164ce58198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucAddr_divAddress']/table/tbody/tr[3]/td[2]/ul/li/input</value>
      <webElementGuid>f7ed74eb-7258-4135-af7e-c1da40fc32c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>0db31a99-cc34-45ba-823b-66f3caaceb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAddr$ucLookupZipCode$uclZipCode$txt' and @type = 'text' and @id = 'ucAddr_ucLookupZipCode_uclZipCode_txt']</value>
      <webElementGuid>797f17a0-243f-47d4-b62b-66932a6fa03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
