<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH_ECONOMY_SECTOR</name>
   <tag></tag>
   <elementGuidId>444bb899-0101-41fc-a8b8-bd3b67863016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UCRefMasterSekEko_ucLookupRefMaster_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UCRefMasterSekEko_ucLookupRefMaster_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>740081cd-90c8-4779-b81e-23a9a45f9d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>82c3172f-d054-4173-b7e1-887d0c264006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UCRefMasterSekEko$ucLookupRefMaster$imb</value>
      <webElementGuid>7d0a8c2c-2e8a-4dda-bfbf-3f44ccc4940d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UCRefMasterSekEko_ucLookupRefMaster_imb</value>
      <webElementGuid>322101cf-6ed2-49d5-a55e-fe729ad0b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>b415f915-87ad-4299-84eb-626adfdc1b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnUCRefMasterSekEko_ucLookupRefMaster');</value>
      <webElementGuid>0144a01b-529e-4988-b17c-448d7ba8559e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UCRefMasterSekEko_ucLookupRefMaster_imb&quot;)</value>
      <webElementGuid>0cf3bb56-2f0b-403e-8bcb-31cfad24fd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>de06d8a7-fe4f-4b7c-9ed6-21266a902934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UCRefMasterSekEko_ucLookupRefMaster_imb']</value>
      <webElementGuid>59f972c2-baa6-4ae4-ab14-ad0b0e2486b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dDataRestrukturisasi']/table/tbody/tr[4]/td[2]/ul/li/input[2]</value>
      <webElementGuid>7c0f2320-9226-4aee-8242-07cf670a3951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/ul/li/input[2]</value>
      <webElementGuid>dbfb376a-cfab-47fd-b7ae-f13df018b03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'UCRefMasterSekEko$ucLookupRefMaster$imb' and @id = 'UCRefMasterSekEko_ucLookupRefMaster_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>67f6fbce-bdec-484d-b26d-edcd1b744252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
