<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Sektor Ekonomi</name>
   <tag></tag>
   <elementGuidId>a1e92e18-d19b-492c-9088-4cf242465233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3de14576-0a0e-4ff0-8770-a66c4673c85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>725ba7bc-549b-4d06-a0f1-903915232ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>2d049f38-1b3b-410b-afb7-160911b8fbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;UCRefMasterSekEko$ucLookupRefMaster$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>70ce1953-ed18-4eff-aecb-140a3f4f8aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>d9529b8b-5737-4537-8224-6730c9aa4540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>35933b53-f2a4-4aa8-9437-8ced15413e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>0ba310a5-5e9e-4e60-bd8c-7c6021a7941a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>e7a18f24-ceaf-433f-8309-d1baf15eac92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>fe79e155-5c4a-4f50-b79e-a4c040cb2d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[3]</value>
      <webElementGuid>d1ac8cb2-1126-4880-95af-04eca885ec51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sektor Ekonomi Penggunaan Pembiayaan'])[1]/following::a[1]</value>
      <webElementGuid>735e6f94-893e-4d85-bb9f-3ada65c80fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOOK UP - Sektor Ekonomi Penggunaan Pembiayaan'])[1]/following::a[1]</value>
      <webElementGuid>12755820-196e-46ee-b495-c209d7c7dd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[3]/preceding::a[1]</value>
      <webElementGuid>bc859cdb-35ae-4c37-81ed-1b2f5af76bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;UCRefMasterSekEko$ucLookupRefMaster$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>d58334b7-b336-4519-b6c4-adc99874d30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>ef7cecc9-f0f5-4084-b328-6581eaeed096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;UCRefMasterSekEko$ucLookupRefMaster$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;UCRefMasterSekEko_ucLookupRefMaster_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>00f62915-61fd-430e-8a75-1840a1043bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
