<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TenortxtInput</name>
   <tag></tag>
   <elementGuidId>5978368b-b483-4633-bc9f-08000e45a40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINTenor_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINTenor_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73d54b89-fce7-4ca8-9e28-a156442e4b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINTenor$txtInput</value>
      <webElementGuid>0d842d6a-35e4-414a-a726-3652c565ca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb24f66a-7bc7-412f-a8e8-80fec4e4b0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>702a2c38-5927-4681-a081-e8391fa1390b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINTenor$txtInput\',\'\')', 0)</value>
      <webElementGuid>6c5db5c3-9799-4764-9e23-1c9d59aa6c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>9fefd729-0d7a-48d6-9846-18e5226f60a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINTenor_txtInput</value>
      <webElementGuid>ad981de3-c6e5-4247-a024-6b782748cad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>608bde63-90ae-4c1d-838f-9b5c997480c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return (event.keyCode!=13);</value>
      <webElementGuid>0ef7770c-1d36-485d-b15b-ff1176a8af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValueInteger('ucINTenor_txtInput','ucINTenor_hdnInput','ucINTenor_txtInputDummy');</value>
      <webElementGuid>2734428a-6d1c-4890-b3ed-b59129372af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINTenor_txtInput');</value>
      <webElementGuid>c62543c0-48e4-451d-b7d8-eb34ebe9a93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINTenor_txtInput&quot;)</value>
      <webElementGuid>3f4bc27e-e41f-4593-a44c-d3b4fea88455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>ef56e1c2-d513-4dcf-8642-c44406ebe9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINTenor_txtInput']</value>
      <webElementGuid>66cfa7ff-d310-481e-b05e-8b3add8f3324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAppData']/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>3575557b-3f9d-41b3-afd1-510c49836faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>856f41be-1c73-478b-9113-990156b7a71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINTenor$txtInput' and @type = 'text' and @id = 'ucINTenor_txtInput']</value>
      <webElementGuid>fd1725a0-d04c-4b0b-9a48-376a7cdafca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
