<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtKecamatan</name>
   <tag></tag>
   <elementGuidId>d67b1527-8a2c-437a-92b2-daee36986912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_txtKecamatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_txtKecamatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cc0b8e7-c008-4e44-815c-a83f27240ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$txtKecamatan</value>
      <webElementGuid>c895a8af-a989-4a24-9db5-a69d66819f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acedcb5b-11e6-4b5f-9f1d-ca5dcf8cd794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>86247c5d-bf74-4940-9ebe-64b426fa95f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_txtKecamatan</value>
      <webElementGuid>94875889-6ebb-425c-83cb-e59a6ed03044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>cf234b42-9fc2-46f9-8737-0b315598f8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_txtKecamatan&quot;)</value>
      <webElementGuid>471b3617-7562-4ac2-939a-ae8ac95274ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>3b908c2f-98d1-47b9-9fe8-9443a1420069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_txtKecamatan']</value>
      <webElementGuid>99f184dd-0bb7-4509-bc36-87a96a2055c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ucAddr_trKecamatan']/td[2]/input</value>
      <webElementGuid>d0dd8b9e-a9f3-4066-a8d4-5b842c718b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>a342e187-7111-4f55-9b1e-fc910f88e504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAddr$txtKecamatan' and @type = 'text' and @id = 'ucAddr_txtKecamatan']</value>
      <webElementGuid>2f3c3af5-726b-415d-81d2-cbbd7d743ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
