<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtKelurahan</name>
   <tag></tag>
   <elementGuidId>841e5697-231e-445b-990d-6e32c25179ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_txtKelurahan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_txtKelurahan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50f71ba9-4335-4c61-a1b7-338a554da949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$txtKelurahan</value>
      <webElementGuid>a88d65c6-4945-467a-8a39-b9af96044dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d5c7250-35b1-4a8c-b82d-1c4a5acc6964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>5492a49e-c434-4559-ad8e-d4a873296b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_txtKelurahan</value>
      <webElementGuid>7df613dc-a986-40a5-88a8-016db9092c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>df67580d-8093-4e27-a25b-4f618fc86415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_txtKelurahan&quot;)</value>
      <webElementGuid>9a4c4ee3-6b9a-45eb-90f1-34b5266a3923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>b23aec0f-5406-46d7-bc72-4624182f34cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_txtKelurahan']</value>
      <webElementGuid>f66e6e61-8609-4577-9423-a6f68bd70d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ucAddr_trKelurahan']/td[2]/input</value>
      <webElementGuid>d013a104-f075-4f96-9b46-36953df9739d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>abb838c7-7927-4da3-8d0b-5d44afe2ce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAddr$txtKelurahan' and @type = 'text' and @id = 'ucAddr_txtKelurahan']</value>
      <webElementGuid>a648fc09-94c1-4f9e-909f-831c46a6c737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
