<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtProspectNo</name>
   <tag></tag>
   <elementGuidId>167c54b2-5727-4356-be98-ae436c00d9e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtProspectNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtProspectNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34e49440-6e8a-4cca-84e9-805490239bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProspectNo</value>
      <webElementGuid>67e313f1-eb4a-4916-9b04-aef5d5d8ccea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a685585-b232-48f2-8ef2-6b666db59c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2a4bcb85-941a-4d5d-80ee-a29036b1284d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProspectNo</value>
      <webElementGuid>7fabf961-0cd1-4859-9db1-74b64febb706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProspectNo&quot;)</value>
      <webElementGuid>248fa648-8fdc-47f3-b713-c93e120df390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru3/Bro 4/iframe_Term  Condition_appForm</value>
      <webElementGuid>211a3d6c-795b-42be-9cff-faa1cc6ab422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProspectNo']</value>
      <webElementGuid>66933482-7e09-4cc8-be8a-f41bf61c7045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trProspectNo']/td[2]/input</value>
      <webElementGuid>f0cb367e-91b9-4b8f-bca4-e418494f0276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f9a527e7-176c-47a3-9a9b-1468099bfd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtProspectNo' and @type = 'text' and @id = 'txtProspectNo']</value>
      <webElementGuid>9c9156b3-7ce4-43f7-b1d5-2c0eb34655f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
