<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEARCH</name>
   <tag></tag>
   <elementGuidId>9005ccef-6729-4c1a-981d-fb0151ab0215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2c00505-9e75-42c6-9254-cf6f7b9abdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>6fbda9f8-a189-48f5-8219-132dd0d33c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>997616aa-cb29-4b14-a9e1-6eca366d1378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupProdOffer$uclProductOffering$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>e0a27ec3-81dc-47db-ab26-9f9efaaf25d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>f5390e8f-ec17-405f-bf95-ea08a4b395d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>d65b643c-64ff-42af-b412-1744567ccd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Baru/Page_New Confins - Main/Page_New Confins - Main/iframe_Welcome, Nova Dwihartanto, MALANG, Credit Admin_mainPage (1) (1)</value>
      <webElementGuid>3727c654-6837-4569-bfd6-2e3c433c15d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>c5b14983-d119-40db-a862-f608406120c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>f8bd2f77-085c-4f95-b5a5-5be31726ab05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[2]</value>
      <webElementGuid>2cc8dc73-8a11-4a89-96d0-e9c026b29086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Offering Name'])[3]/following::a[1]</value>
      <webElementGuid>6f8166f0-24b7-4b54-9e18-22650ac019d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Offering Code'])[1]/following::a[1]</value>
      <webElementGuid>5d740321-c397-444a-be12-645b0536ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[2]/preceding::a[1]</value>
      <webElementGuid>29cf5d2c-c522-4639-ac42-d01bf49ba18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::a[2]</value>
      <webElementGuid>982901e7-5a1a-467a-af7e-4e06d23d3046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupProdOffer$uclProductOffering$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>f87be6e9-5375-4b41-925e-3ef7ad7eb26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>41ac78d2-ad9e-434e-915b-495b3fd33519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupProdOffer$uclProductOffering$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>4a4a18a5-8081-4ea0-aab3-c5d780395daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
